export enum Configuration {
    DOCUMENT = 'DOCUMENT',
    SECURITY = 'SECURITY',
    CONFIGURATION = 'CONFIGURATION',
    SYSTEM = 'SYSTEM',
    TEMPLATE = 'TEMPLATE',
    GENERAL = 'GENERAL'
}

export enum Permission {
    HOME = 'HOM-000',
    //Documents
    DOCUMENTS = 'DOC-100',
    EDIT_VIEW_DOCUMENT = 'DOC-101',
    REGISTER_DOCUMENT = 'DOC-101-1',
    EDIT_DOCUMENTS = 'DOC-101-2',
    IN_REVIEW_DOCUMENTS = 'DOC-102',
    APPROVED_DOCUMENTS = 'DOC-103',
    ARCHIVED_DOCUMENTS = 'DOC-104',
    //Templates
    TEMPLATES = 'PLA-200',
    AVAILABLE_TEMPLATES = 'PLA-200',
    //Security
    SECURITY = 'SEG-400',
    PERMISSIONS = 'SEG-401',
    ROLES = 'SEG-402',
    USERS = 'SEG-404',
    ACCOUNTS = 'SEG-405',
    //Configuration
    CONFIGURATION = 'CONF-500',
    DOCUMENT_VARIABLES = 'CONF-501',
    DOCUMENT_TYPES = 'CONF-502',
    //System
    SYSTEM = 'SIS-600',
    SIS = '601',
    ANALYTIC = 'SIS-602'
}
