name: Build and Deploy to Azure Web App - sodocu

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setea Node.js 18 (compatibilidad con Next.js)
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Instalar dependencias y build (opcional, para verificar errores antes del deploy)
      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      # 4. Publicar directamente a Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sodocu'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8F903CF79A5341ED882427E8497A65AA }}
          package: .
