name: Deploy NestJS to Azure

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name
  NODE_VERSION: '20.x'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build NestJS
        run: npm run build
      
      - name: Run tests (optional)
        run: npm run test
      
      - name: Zip deployment files
        run: |
          mkdir -p deployment
          cp -r dist package.json package-lock.json .env* deployment/
          cd deployment && zip -r ../deployment.zip .
      
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: deployment.zip
